steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--target', 'cat', '-t', 'gcr.io/$PROJECT_ID/go-api-cat:${_ENV_NAME}-${_VERSION}', '.']
    id: build-cat

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--target', 'dog', '-t', 'gcr.io/$PROJECT_ID/go-api-dog:${_ENV_NAME}-${_VERSION}', '.']
    id: build-dog

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/go-api-cat:${_ENV_NAME}-${_VERSION}']
    id: push-cat

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/go-api-dog:${_ENV_NAME}-${_VERSION}']
    id: push-dog

images:
  - 'gcr.io/$PROJECT_ID/go-api-cat:${_ENV_NAME}-${_VERSION}'
  - 'gcr.io/$PROJECT_ID/go-api-dog:${_ENV_NAME}-${_VERSION}'